import * as THREE from "three";
import { useTexture, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useRef } from "react";

/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: jemepousse (https://sketchfab.com/jemepousse)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/356c773c4b9a45d8b9d4aa04c60ecb27
title: Red City
*/
export default function CityModel() {
    const group = useRef<THREE.Group>(null!)

    const { nodes, materials } = useGLTF('/scene-draco.glb')
    const blueTexture = useTexture('/base_blue.jpg')

    useEffect(() => {
        if (materials && blueTexture) {
            (materials.Scene_Root as THREE.MeshBasicMaterial).map = blueTexture
        }
    },[materials, blueTexture])

    useFrame(() => {
        if (!group.current) return
        group.current.rotation.y += 0.0003
    })

    if (!nodes || !materials) return null

    return (
    <>
      <group ref={group} scale={0.001} position={[0, -5, -150]} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[-102253.52, -210688.86, -17050.52]}>
            <mesh material={materials.Scene_Root} geometry={(nodes.mesh_0 as THREE.Mesh).geometry} />
            <mesh material={materials.Scene_Root} geometry={(nodes.mesh_1 as THREE.Mesh).geometry} />
            <mesh material={materials.Scene_Root} geometry={(nodes.mesh_2 as THREE.Mesh).geometry} />
            <mesh material={materials.Scene_Root} geometry={(nodes.mesh_3 as THREE.Mesh).geometry} />
          </group>
          <mesh position={[250000, -200000, 50000]}>
            <sphereGeometry args={[30000, 32, 32]} />
            <meshBasicMaterial color="#363636" />
          </mesh>
        </group>
      </group>
      </>
    )
  }

  useGLTF.preload('/scene-draco.glb')